services:
  sms:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: "true"
    ports:
      - "8000:8000"
    volumes:
      - ./sms:/sms
    command: >
      sh -c "python manage.py migrate && 
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=supersecretpassword
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=supersecretpassword

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  dev-db-data:
  redis-data: