# Generated by Django 5.2 on 2025-05-05 22:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_is_guardian'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['stage', 'level', 'stream'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this class is active in the current academic year', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='class',
            name='max_students',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of students allowed in this class', verbose_name='Maximum Students'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school', verbose_name='School'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.PositiveSmallIntegerField(help_text='Numerical ordering within stage (1-6 for primary, 1-3 for JHS/SHS)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='class',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='For SHS only (e.g. Science, Arts etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='student.programme', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='class',
            name='stage',
            field=models.CharField(choices=[('KG', 'Kindergarten'), ('PR', 'Primary School'), ('JHS', 'Junior High School'), ('SHS', 'Senior High School')], db_index=True, max_length=5, verbose_name='Educational Stage'),
        ),
        migrations.AlterField(
            model_name='class',
            name='stream',
            field=models.CharField(help_text="Stream/section designation (e.g., 'A', 'Gold')", max_length=128, verbose_name='Stream'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'stage', 'level', 'stream', 'programme')},
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school'], name='student_cla_school__a511ce_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['is_active'], name='student_cla_is_acti_3eec13_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'stage', 'level'], name='student_cla_school__caa046_idx'),
        ),
    ]
