# Generated by Django 5.2 on 2025-05-03 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='physical_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
