# Generated by Django 5.2 on 2025-05-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_school_alter_school_physical_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_guardian',
        ),
    ]
